spring.application.name=cabtruckapi

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cabtruckapi_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.expiracao=1
security.jwt.chave-assinatura=cabtruckapiSecretKeyJwt2024@UFJF#SpringBoot
